# Generated by Django 3.2 on 2022-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrant',
            options={'verbose_name': 'Entrant', 'verbose_name_plural': 'Entrants'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentcard',
            options={'verbose_name': 'Student Card', 'verbose_name_plural': 'Student Cards'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='userdocument',
            options={'verbose_name': 'User Document', 'verbose_name_plural': 'User Documents'},
        ),
        migrations.AlterModelOptions(
            name='usertag',
            options={'verbose_name': 'User Tag', 'verbose_name_plural': 'User Tags'},
        ),
    ]
