# Generated by Django 3.2 on 2022-11-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221126_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrant',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='entrant',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='studentcard',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='studentcard',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userdocument',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userdocument',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
