# Generated by Django 3.2 on 2022-11-15 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
