# Generated by Django 3.2 on 2022-11-22 16:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('users', '0004_auto_20221115_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcard',
            old_name='creditedOrder',
            new_name='credited_order',
        ),
        migrations.RenameField(
            model_name='studentcard',
            old_name='issueDate',
            new_name='issue_date',
        ),
        migrations.RenameField(
            model_name='studentcard',
            old_name='validBy',
            new_name='valid_by',
        ),
        migrations.RenameField(
            model_name='userdocument',
            old_name='fileType',
            new_name='file_type',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='authorOccupation',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='authorPicture',
        ),
        migrations.AddField(
            model_name='quote',
            name='author_occupation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Author Occupation'),
        ),
        migrations.AddField(
            model_name='quote',
            name='author_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Author Picture'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(max_length=250, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=wagtail.fields.RichTextField(help_text='Text', verbose_name='Text'),
        ),
    ]
