# Generated by Django 3.2 on 2022-11-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20221129_2247"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdocument",
            name="file_type",
        ),
    ]
