# Generated by Django 3.2 on 2022-11-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userdocument_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcard',
            name='card_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Student Card Id'),
        ),
    ]
