# Generated by Django 3.2 on 2022-11-22 17:34

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221122_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertag',
            name='users',
        ),
        migrations.AlterField(
            model_name='usertag',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Text', null=True, verbose_name='Text'),
        ),
    ]
