# Generated by Django 3.2 on 2023-01-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230105_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
    ]
