# Generated by Django 3.2 on 2023-01-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230105_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Achievement', 'verbose_name_plural': 'Achievements'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'verbose_name': 'User achievement', 'verbose_name_plural': 'User achievements'},
        ),
        migrations.AlterModelOptions(
            name='usercontact',
            options={'verbose_name': 'User contact', 'verbose_name_plural': 'User contacts'},
        ),
        migrations.AlterUniqueTogether(
            name='usercontact',
            unique_together={('user_profile', 'title', 'value')},
        ),
    ]
