# Generated by Django 3.2 on 2022-12-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=100, verbose_name='Phone/Email/Social')),
                ('type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('social', 'Social')], default='phone', max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('contacts', models.ManyToManyField(blank=True, null=True, to='core.Contact', verbose_name='Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MainComponentsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.URLField(blank=True, max_length=500, null=True, verbose_name='Telegram')),
                ('header', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.header')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='header',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='core.Location', verbose_name='Location Addresses'),
        ),
    ]
