# Generated by Django 3.2 on 2022-12-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221201_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Phone/Email/Social'),
        ),
    ]
