# Generated by Django 3.2 on 2022-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='core.Contact', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='header',
            name='locations',
            field=models.ManyToManyField(blank=True, to='core.Location', verbose_name='Location Addresses'),
        ),
    ]
