# Generated by Django 3.2 on 2022-12-01 13:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221201_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('right_description', wagtail.fields.RichTextField(verbose_name='Right Description')),
                ('show_contact_form', models.BooleanField(default=True, verbose_name='Show Contact Form?')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Phone/Почта/Social'),
        ),
        migrations.AlterField(
            model_name='maincomponentssettings',
            name='footer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.footer'),
        ),
    ]
