# Generated by Django 3.2 on 2022-12-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('core', '0005_auto_20221201_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainComponentsSettings',
            new_name='MainContentSettings',
        ),
    ]
