# Generated by Django 3.2 on 2022-12-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('core', '0013_maincontentsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='menus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menus.menu', verbose_name='Menu'),
        ),
    ]
