# Generated by Django 3.2 on 2022-12-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_header_menus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='menus',
            new_name='menu',
        ),
    ]
