# Generated by Django 3.2 on 2022-12-03 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
        ('core', '0015_rename_menus_header_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontentsettings',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Logo'),
        ),
    ]
