# Generated by Django 3.2 on 2022-12-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_maincontentsettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontentsettings',
            name='short_org_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Short Organization Name'),
        ),
    ]
