# Generated by Django 3.2 on 2022-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_maincontentsettings_short_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontentsettings',
            name='show_last_news_marquee',
            field=models.BooleanField(default=True, verbose_name='Show Last News Marquee'),
        ),
    ]
