# Generated by Django 3.2 on 2022-12-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_maincontentsettings_show_last_news_marquee'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontentsettings',
            name='org_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Organization Name'),
        ),
    ]
