# Generated by Django 3.2 on 2022-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_maincontentsettings_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincontentsettings',
            name='show_last_news_marquee',
        ),
        migrations.AddField(
            model_name='header',
            name='show_last_news_marquee',
            field=models.BooleanField(default=True, verbose_name='Show Last News Marquee'),
        ),
    ]
