# Generated by Django 3.2 on 2022-12-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
        ('core', '0020_auto_20221203_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg', verbose_name='Icon')),
            ],
        ),
        migrations.AddField(
            model_name='footer',
            name='socials',
            field=models.ManyToManyField(blank=True, to='core.Social', verbose_name='Socials'),
        ),
        migrations.AddField(
            model_name='header',
            name='socials',
            field=models.ManyToManyField(blank=True, to='core.Social', verbose_name='Socials'),
        ),
    ]
