# Generated by Django 3.2 on 2022-12-03 13:18

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20221203_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='socials',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.Social', verbose_name='Socials'),
        ),
    ]
