# Generated by Django 3.2 on 2022-12-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_header_socials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='social',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
