# Generated by Django 3.2 on 2022-12-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20221203_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={},
        ),
        migrations.RemoveField(
            model_name='social',
            name='sort_order',
        ),
    ]
