# Generated by Django 3.2 on 2022-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20221203_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincontentsettings',
            name='yandex_map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Yandex Url'),
        ),
    ]
