# Generated by Django 3.2 on 2022-12-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_maincontentsettings_yandex_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontentsettings',
            name='yandex_map_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Yandex Map Url'),
        ),
    ]
