# Generated by Django 3.2 on 2022-12-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('svg', '0002_auto_20221206_1738'),
        ('core', '0029_auto_20221206_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincontentsettings',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='svg.svgtyped', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='svg.svgtyped', verbose_name='Icon'),
        ),
    ]
