# Generated by Django 3.2 on 2022-12-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20221206_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Phone/Email/Social'),
        ),
    ]
