# Generated by Django 3.2 on 2022-12-06 16:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='menu',
            field=wagtail.fields.StreamField([('url', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Name', max_length=100)), ('url', wagtail.blocks.URLBlock('Url'))])), ('site_page', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(help_text='Name', max_length=100)), ('page', wagtail.blocks.PageChooserBlock(help_text='Page'))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
