# Generated by Django 3.2 on 2023-01-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_footer_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='socials',
            field=models.ManyToManyField(blank=True, to='core.Social', verbose_name='Socials'),
        ),
        migrations.AlterField(
            model_name='header',
            name='socials',
            field=models.ManyToManyField(blank=True, to='core.Social', verbose_name='Socials'),
        ),
    ]
