# Generated by Django 3.2 on 2023-01-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_mainurlssettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialSettings',
        ),
    ]
