# Generated by Django 3.2 on 2023-01-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_mainurlssettings_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainurlssettings',
            name='a',
        ),
    ]
