# Generated by Django 3.2 on 2022-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dateEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateevent',
            options={'verbose_name': 'Date Event', 'verbose_name_plural': 'Date Events'},
        ),
        migrations.AlterModelOptions(
            name='dateeventpost',
            options={'verbose_name': 'Date Event Post', 'verbose_name_plural': 'Date Event Posts'},
        ),
    ]
