# Generated by Django 3.2 on 2022-11-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposttag',
            old_name='blog_post',
            new_name='content_object',
        ),
    ]
