# Generated by Django 3.2 on 2022-12-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0003_alter_blogpostpage_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='post_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Picture'),
        ),
    ]
