# Generated by Django 3.2 on 2022-12-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('blog', '0006_alter_blogpostpage_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostindexpage',
            name='facePicture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Face Picture'),
        ),
        migrations.AddField(
            model_name='blogpostindexpage',
            name='faceTitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Face Title'),
        ),
    ]
