# Generated by Django 3.2 on 2022-12-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221215_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostindexpage',
            old_name='facePicture',
            new_name='face_picture',
        ),
        migrations.RenameField(
            model_name='blogpostindexpage',
            old_name='faceTitle',
            new_name='face_title',
        ),
    ]
