# Generated by Django 3.2 on 2022-11-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='n',
        ),
    ]
