# Generated by Django 3.2 on 2022-12-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20221222_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpostpage',
            name='updated_at',
        ),
    ]
