# Generated by Django 3.2 on 2022-11-29 18:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221128_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
