# Generated by Django 3.2 on 2022-11-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('educationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculties', to='education.educationtype', verbose_name='Education Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specializations', to='education.faculty', verbose_name='Specialization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecializationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='education.specialization', verbose_name='Specialization')),
                ('subjects', models.ManyToManyField(related_name='groups', to='education.Subject', verbose_name='Subjects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
