# Generated by Django 3.2 on 2022-11-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="educationtype",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="educationtype",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="faculty",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="specialization",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="specialization",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="specializationgroup",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="specializationgroup",
            old_name="updatedAt",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
