# Generated by Django 3.2 on 2022-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationtype',
            options={'verbose_name': 'Education Type', 'verbose_name_plural': 'Education Types'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='specializationgroup',
            options={'verbose_name': 'Specialization Group', 'verbose_name_plural': 'Specialization Groups'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
