# Generated by Django 3.2 on 2022-11-30 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_auto_20221128_2049"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faculty",
            old_name="educationType",
            new_name="education_type",
        ),
        migrations.AlterField(
            model_name="specialization",
            name="faculty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specializations",
                to="education.faculty",
                verbose_name="Faculty",
            ),
        ),
    ]
