# Generated by Django 3.2 on 2023-01-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_teacher_groups'),
        ('education', '0004_auto_20221130_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='education.specializationgroup', verbose_name='Group')),
                ('subjects', models.ManyToManyField(related_name='group_teachers', to='education.Subject', verbose_name='Subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='users.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Group Teacher',
                'verbose_name_plural': 'Group Teachers',
            },
        ),
    ]
