# Generated by Django 3.2 on 2022-11-03 17:06

import authentication.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Phone Number')),
                ('firstName', models.CharField(max_length=40, verbose_name='Name')),
                ('lastName', models.CharField(max_length=80, verbose_name='Surname')),
                ('patronymic', models.CharField(max_length=80, verbose_name='Patronymic')),
                ('picture', models.ImageField(upload_to='userPictures/', verbose_name='Profile Picture')),
                ('bgPicture', models.ImageField(upload_to='userBgPictures/', verbose_name='Profile Background Picture')),
                ('isStaff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('isSuperuser', models.BooleanField(default=False, verbose_name='Is Super User')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', authentication.managers.CustomUserManager()),
            ],
        ),
    ]
