# Generated by Django 3.2 on 2022-11-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bgPicture',
            field=models.ImageField(blank=True, null=True, upload_to='userBgPictures/', verbose_name='Profile Background Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='userPictures/', verbose_name='Profile Picture'),
        ),
    ]
