# Generated by Django 3.2 on 2022-11-22 17:34

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221122_2134'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(related_name='users', to='users.UserTag', verbose_name='Tags'),
        ),
    ]
