# Generated by Django 3.2 on 2022-11-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_studentcard_card_id'),
        ('authentication', '0004_auto_20221128_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(related_name='users', to='users.UserTag', verbose_name='Tags'),
        ),
    ]
