# Generated by Django 3.2 on 2023-01-15 13:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail_headless_preview.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('authentication', '0007_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('is_gos_uslugi_enabled', models.BooleanField(default=True, verbose_name='Enable GosUslugi Login')),
                ('is_password_enabled', models.BooleanField(default=True, verbose_name='Enable Password Login')),
                ('is_email_code_enabled', models.BooleanField(default=True, verbose_name='Enable Email Code Login')),
                ('is_phone_code_enabled', models.BooleanField(default=True, verbose_name='Enable Phone Code Login')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, 'wagtailcore.page'),
        ),
    ]
