# Generated by Django 3.2 on 2023-01-15 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_loginpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpage',
            name='is_email_code_enabled',
        ),
    ]
