# Generated by Django 3.2 on 2023-01-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('authentication', '0010_loginpage_is_vkontakte_enabled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginPage',
        ),
    ]
