# Generated by Django 3.2 on 2023-01-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_loginpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bg_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
    ]
