# Generated by Django 3.2 on 2023-02-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_rename_signed_up_user_is_signed_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
    ]
