# Generated by Django 3.2 on 2023-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20230215_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email', 'mobile')},
        ),
    ]
