# Generated by Django 3.2 on 2022-11-18 20:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221118_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='faceBody',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.CharBlock(help_text='Основной Текст', max_length=255)), ('shortText', wagtail.blocks.CharBlock(help_text='Короткий Текст', max_length=255)), ('size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Маленький'), ('normal', 'Обычный'), ('big', 'Большой')], help_text='Размер Шрифта'))], blank=True, use_json_field=None),
        ),
    ]
