# Generated by Django 3.2 on 2022-11-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0003_homepage_facebody'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='faceBg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Лицевая фоновая картинка'),
        ),
    ]
