# Generated by Django 3.2 on 2022-11-18 20:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_facebody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='faceBody',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(help_text='Основной Текст', max_length=255)), ('shortText', wagtail.blocks.CharBlock(help_text='Короткий Текст', max_length=255)), ('size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Маленький'), ('normal', 'Обычный'), ('big', 'Большой')], help_text='Размер Шрифта'))]))], use_json_field=True),
        ),
    ]
