# Generated by Django 3.2 on 2022-11-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20221124_2126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceheading",
            name="text",
            field=models.CharField(blank=True, max_length=255, verbose_name="Text"),
        ),
    ]
