# Generated by Django 3.2 on 2022-11-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221128_2049'),
        ('home', '0012_alter_homepage_more_info_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, related_name='home_page', to='news.News'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_use_type',
            field=models.CharField(choices=[('last', 'Last News'), ('chosen', 'Chosen News')], default='last', max_length=100, verbose_name='News Use Type'),
        ),
    ]
