# Generated by Django 3.2 on 2022-11-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221130_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='news',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='news_use_type',
        ),
    ]
