# Generated by Django 3.2 on 2022-12-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedSvg',
            fields=[
            ],
            options={
                'verbose_name': 'Svg',
                'verbose_name_plural': 'Svg List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wagtailsvg.svg',),
        ),
    ]
