# Generated by Django 3.2 on 2022-12-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Custom URL'),
        ),
        migrations.AlterField(
            model_name='menuitemlink',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Custom URL'),
        ),
        migrations.AlterField(
            model_name='menuitemlinkgroup',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Custom URL'),
        ),
    ]
