# Generated by Django 3.2 on 2022-11-20 18:21

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemlink',
            name='menu_item',
        ),
        migrations.CreateModel(
            name='MenuItemLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Custom URL ')),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False, verbose_name='Open in new tab')),
                ('menu_item', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_groups', to='menus.menuitem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuitemlink',
            name='link_group',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_groups', to='menus.menuitemlinkgroup'),
        ),
    ]
