# Generated by Django 3.2 on 2022-11-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionApplications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionapplication',
            options={'verbose_name': 'Admission Application', 'verbose_name_plural': 'Admission Applications'},
        ),
    ]
