# Generated by Django 3.2 on 2022-11-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('contentMainSettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headers', to='menus.menu'),
        ),
        migrations.AddField(
            model_name='footer',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footers', to='menus.menu'),
        ),
    ]
